package edu.pucmm.severless.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "reservation")
public class Reservation {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String reservationId;

    @DynamoDBAttribute
    private String Id;

    @DynamoDBAttribute
    private String nombre;

    @DynamoDBAttribute
    private String carrera;

    @DynamoDBAttribute
    private String laboratorio;

    @DynamoDBAttribute
    private LocalDateTime fechaReserva;

    public Reservation(LocalDateTime fechaReserva,String reservationId, String id, String nombre, String carrera, String laboratorio) {
        this.reservationId = reservationId;
        Id = id;
        this.nombre = nombre;
        this.carrera = carrera;
        this.laboratorio = laboratorio;
        this.fechaReserva = fechaReserva;
    }

    public String getReservationId() {
        return reservationId;
    }
    public void setReservationId(String reservationId) {
        this.reservationId = reservationId;
    }

    public String getId() {
        return Id;
    }

    public void setId(String id) {
        Id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCarrera() {
        return carrera;
    }

    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }

    public String getLaboratorio() {
        return laboratorio;
    }

    public void setLaboratorio(String laboratorio) {
        this.laboratorio = laboratorio;
    }

    public LocalDateTime getFechaReserva() {
        return fechaReserva;
    }

    public void setFechaReserva(LocalDateTime fechaReserva) {
        this.fechaReserva = fechaReserva;
    }
}
