package com.example.demo_serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "Reservation")
public class Reservation {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String reservationId;

    @DynamoDBAttribute(attributeName="id")
    private String id;

    @DynamoDBAttribute(attributeName = "nombre")
    private String nombre;
    @DynamoDBAttribute(attributeName = "carrera")
    private String carrera;
    @DynamoDBAttribute(attributeName = "laboratorio")
    private String laboratorio;

    @DynamoDBAttribute(attributeName = "fechaReserva")
    private LocalDateTime fechaReserva;

    public Reservation(){

    }

    public Reservation(String id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Reservation(String id, String nombre, String carrera, String laboratorio) {
        this.id = id;
        this.nombre = nombre;
        this.carrera = carrera;
        this.laboratorio = laboratorio;
    }

    public String getReservationId() {
        return reservationId;
    }

    public void setReservationId(String reservationId) {
        this.reservationId = reservationId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getLaboratorio() {
        return laboratorio;
    }

    public void setLaboratorio(String laboratorio) {
        this.laboratorio = laboratorio;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    public String getCarrera() {
        return carrera;
    }

    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }

    public LocalDateTime getFechaReserva() {
        return fechaReserva;
    }

    public void setFechaReserva(LocalDateTime fechaReserva) {
        this.fechaReserva = fechaReserva;
    }

    @Override
    public String toString() {
        return "Reservation{" +
                "id=" + id +
                ", nombre='" + nombre + '\'' +
                ", carrera='" + carrera + '\'' +
                ", laboratorio='" + laboratorio + '\'' +
                '}';
    }
}
